### PR TITLE
ADD:add a go to top button (dynamic)

### PR DESCRIPTION
**Pull request by rahat2134**
*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*
Yes, I have read the guidelines
Issue #38 

## Describe your changes
I change nothing, I have added the functionality of a button (go to top) which is helpful in taking you on the homepage (uppest part). We use this functionality in day to day life .
*Clearly and concisely describe what's in this pull request. Include screenshots, if necessary.*
Screenshot 2024-01-15 at 1 50 50 AM
Adding a "Go to Top" button provides a simple and user-friendly solution for quick navigation to the top of the page.

### CODE REVIEW

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Instead of "Go to Top", use a arrow svg, also customise it for grayscale, if screen is dark, make grayscale to 1 else for light mode have a black arrow

**Comment by rahat2134** [comment]
@anand-harsh give me sometime, i will resolve this, this is medium-hard category now.

**Comment by anand-harsh** [comment]
> @anand-harsh give me sometime, i will resolve this, this is medium-hard category now.

You just need to replace the text with image, it will fall in easy ones

**Comment by rahat2134** [comment]
@anand-harsh please add tag in this issue of JWOC and difficulty level

**Pull request merged**
