### PR TITLE
[bug]: Remove Unwanted overflows

### PR DESCRIPTION
**Pull request by lusifer65**
fixes: #3 

image

image

image

image

### CODE REVIEW

**Comment by anand-harsh** [comment]
Hi @lusifer65 , overflow is still present on " /subscribe "

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Hi @lusifer65 , overflow is still present on " /subscribe "

**Comment by anand-harsh** [comment]
Hi @lusifer65 it is still not fixed. Kindly check /subscribe page

**Comment by lusifer65** [comment]
fixed #12

**Review by anand-harsh — APPROVED** [review]
LGTM✨

**Pull request merged**
