### PR TITLE
New Intro Video added

### PR DESCRIPTION
**Pull request by rahat2134**
*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*
Yes,
Issue #27 

## Describe your changes
Just add a new relevant video made and edited by me.
*Clearly and concisely describe what's in this pull request. Include screenshots, if necessary.*
Screenshot 2024-01-22 at 1 49 37 AM

### CODE REVIEW

**Comment by rahat2134** [comment]
@anand-harsh please check the pr.

**Comment by anand-harsh** [comment]
Update your branch once

**Comment by rahat2134** [comment]
@anand-harsh done

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Make it autoplay and remove controls from video

**Comment by rahat2134** [comment]
@anand-harsh done

**Review by anand-harsh — APPROVED** [review]
LGTM✨✨

**Pull request merged**
