### PR TITLE
Fixed #9

### LINKED ISSUE #9: Fix Create Course Layout
**Issue:** Fix the layout of Create course page (/admin/createcourse) .The Sidebar for the dashboard should be on right hand side.

### PR DESCRIPTION
**Pull request by Vansh-Narang**
fixed #9

### CODE REVIEW

**Comment by anand-harsh** [comment]
Screenshot_20231023_185001_Chrome

This Sidebar should be at right.

**Review by Vansh-Narang — COMMENTED** [review]
Done with createCourse too

**Comment by Vansh-Narang** [comment]
Screenshot (456)

Done !

**Review by anand-harsh — APPROVED** [review]
LGTM✨

**Pull request merged**
