### PR TITLE
 dashboard layout changed

### LINKED ISSUE #5: Fix dashboard layout
The right sidebar is not properly aligned and the charts section is also not in proper place.

One interested can take this issue

### PR DESCRIPTION
**Pull request by rajvinder-kaur**
fixes #5 
edumi1
edumi 2

### CODE REVIEW

**Comment by anand-harsh** [comment]
Hi @rajvinder-kaur , very nice work. Just one issue is that, dont change sidebar for create course and courses pages

Just change only for dashboard page

**Comment by rajvinder-kaur** [comment]
Ohkay I'll do the mentioned changes 👍🏻

**Comment by anand-harsh** [comment]
Hi @rajvinder-kaur make sure the "/admin/createcourse" page sidebar is on right hand side.

**Comment by anand-harsh** [comment]
Also make sure your fork is up to date and you are working on latest commit.

**Comment by anand-harsh** [comment]
LGTM✨

**Pull request merged**
