### PR TITLE
fixed: Contact page position

### LINKED ISSUE #14: Fix: Footer of Contact page
Issue: Footer of contact ("/contact") page is not stick to bottom of page.

Ref: https://edumi-zeta.vercel.app/contact

### PR DESCRIPTION
**Pull request by abhishek-kumar-91**
fixes #14

I have solved this problem,
Screenshot (109)

### CODE REVIEW

**Comment by anand-harsh** [comment]
image

I think it still have issue for bigger screens

**Comment by abhishek-kumar-91** [comment]
ok, I will be fix now.

**Comment by abhishek-kumar-91** [comment]
@anand-harsh , Can you check now this pr ?

**Comment by abhishek-kumar-91** [comment]
@anand-harsh, Can you merge this pr right now, if pr is solve your problem

**Comment by anand-harsh** [comment]
Hi @abhishek-kumar-91 
Don't use fixed globally on Footer. As we dont want the footer to be fixed on bottom while scroll. Just add footer fixed only on Contact page

**Comment by abhishek-kumar-91** [comment]
@anand-harsh, Now it's done, Check it now and merge this pr #16

**Review by anand-harsh — APPROVED** [review]
LGTM✨

**Pull request merged**
