### PR TITLE
Added new footer

### PR DESCRIPTION
**Pull request by Surajit0573**
*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?* YES

Issue #32

## Describe your changes
Added a new footer as requested.

image

### CODE REVIEW

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Make it fully responsive

Screenshot_20240123_064549_Chrome

**Comment by anand-harsh** [comment]
Hi @Surajit0573 any updates?

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Make it responsive for small devices

**Comment by Surajit0573** [comment]
> Make it responsive for small devices

Ok, give me 1 day more.

**Comment by Surajit0573** [comment]
@anand-harsh 
Screenshot 2024-01-25 234437
Screenshot 2024-01-25 234225
Screenshot 2024-01-25 234323

**Comment by anand-harsh** [comment]
> @anand-harsh Screenshot 2024-01-25 234437 Screenshot 2024-01-25 234225 Screenshot 2024-01-25 234323

push your changes, also update your branch

**Comment by Surajit0573** [comment]
@anand-harsh, already pushed these changes and this branch has no conflicts....!!!?

**Review by anand-harsh — APPROVED** [review]
LGTM✨✨

**Pull request merged**
