### PR TITLE
[UI] : Redesign Footer #128

### PR DESCRIPTION
**Pull request by Prithwi32**
*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*

Issue #128 

## Describe your changes
made footer responsive and changed alignments of contents as per the UI design

https://github.com/anand-harsh/Edumi/assets/115262737/a3d1c73b-dbb7-4aa8-8205-28b81e9246ee

### CODE REVIEW

**Comment by Prithwi32** [comment]
@anand-harsh Sir please could you review my PR

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Make the "Send message" button move down of Edumi text and instead making it smaller.

**Comment by Prithwi32** [comment]
> Make the "Send message" button move down of Edumi text and instead making it smaller.

Okay

**Comment by Prithwi32** [comment]
image


@anand-harsh is this okay now?

**Comment by anand-harsh** [comment]
> image
> 
> @anand-harsh is this okay now?

yes

**Comment by Prithwi32** [comment]
@anand-harsh please could u review PR  and merge...

**Comment by Prithwi32** [comment]
@anand-harsh hello...may i know why again assigned?

**Comment by anand-harsh** [comment]
> @anand-harsh hello...may i know why again assigned?

ignore, I just assigned to make a note or PRs

**Pull request merged**
