### PR TITLE
Adding Restriction for Admin Route

### PR DESCRIPTION
**Pull request by JavidSumra**
- [x] *Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*

Issue #97 

## Describe your changes
By Raising This PR I am Adding Prop on `ProtectedRoute` for Admin Authentication for all Admin Routes

### CODE REVIEW

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir Please Checkout My PR.

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Make it such that when any normal user login then the "Dashboard" button is not visible in sidebase

**Comment by JavidSumra** [comment]
Hey @anand-harsh Sir Please Checkout Now

**Review by anand-harsh — APPROVED** [review]
LGTM✨✨

**Pull request merged**
