### PR TITLE
ADD:LinkedIn,Insta and portfolio of Admin

### PR DESCRIPTION
**Pull request by rahat2134**
*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*
Yes,
Issue #29 

## Describe your changes
I added an portfolio,linkedin and connect instagram to admins account.
*Clearly and concisely describe what's in this pull request. Include screenshots, if necessary.*
image

### CODE REVIEW

**Comment by rahat2134** [comment]
@anand-harsh please check the pr.

**Comment by rahat2134** [comment]
@anand-harsh plz check the pr.

**Comment by anand-harsh** [comment]
Hi @rahat2134 , update your branch

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Kindly update your branch

**Comment by rahat2134** [comment]
image
branch is up to date.

**Comment by anand-harsh** [comment]
LGTM✨✨

**Pull request merged**
