### PR TITLE
Added a feature to add course to user playlist

### PR DESCRIPTION
**Pull request by Divyanshgarg-04**
Added a feature to add course to user playlist

### CODE REVIEW

**Comment by anand-harsh** [comment]
Update your branch once

**Comment by Divyanshgarg-04** [comment]
Did you mean branch name

**Comment by anand-harsh** [comment]
> Did you mean branch name

No

**Comment by anand-harsh** [comment]
> Did you mean branch name

Update your forked repo to latest commit

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Update your forked repo to latest commit

**Pull request closed without merging**
