### PR TITLE
[Feature]: Enhance Sidebar with Icons and Titles. #36

### PR DESCRIPTION
**Pull request by Prithwi32**
*Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*
Yes

Issue #36 

## Describe your changes

Added respective icons in the sidebar

edumi

### CODE REVIEW

**Comment by Prithwi32** [comment]
@anand-harsh Please could you review this PR...

**Review by anand-harsh — CHANGES_REQUESTED** [review]
put icons on the left

**Comment by Prithwi32** [comment]
@anand-harsh could you check changes now..is it okay?

**Review by anand-harsh — APPROVED** [review]
LGTM✨✨

**Pull request merged**
