### PR TITLE
Adding Page and Route to Update Profile

### PR DESCRIPTION
**Pull request by JavidSumra**
- [x] *Have you read the [Contributing Guidelines](https://github.com/jessesquires/.github/blob/master/CONTRIBUTING.md)?*

Issue #49 

## Describe your changes
Adding Page and Route to Update Profile 

image

### CODE REVIEW

**Review by anand-harsh — CHANGES_REQUESTED** [review]
Make it responsive, for small devices, bring all input boxes and content to center of page, and in next lines

**Comment by JavidSumra** [comment]
Changes Done @anand-harsh Sir

**Review by anand-harsh — APPROVED** [review]
LGTM✨✨

**Comment by JavidSumra** [comment]
Hey @anand-harsh please add relevant Labels on this PR

**Pull request merged**
